#!/usr/bin/env python3
"""Explicit Gate 4B compatibility facade."""
# version source: VERSION
from __future__ import annotations

import sys
from pathlib import Path

_candidate_src = Path(__file__).resolve().parents[1] / "src"
if _candidate_src.is_dir() and str(_candidate_src) not in sys.path:
    sys.path.insert(0, str(_candidate_src))

from pwf_governed._legacy.plan_contracts import (
    Any,
    CAPABILITY_COMPATIBILITY,
    CAPABILITY_REF_FIELDS,
    CHECKPOINT_REF_FIELDS,
    CHECKPOINT_STATUSES,
    CONDITION_FIELDS,
    CONDITION_STATUSES,
    CONDITION_TYPES,
    CONTENT_INGEST_RECEIPT_FIELDS,
    CONTENT_JUDGMENT_REASON_CODES,
    CONTENT_JUDGMENT_STATUSES,
    CONTENT_RESULTS,
    CONTRACT_FIELD_SETS,
    CONTRACT_ID_RE,
    CONTRACT_KINDS,
    CURRENT_CONTRACT,
    E0_RESULTS,
    EVOLUTION_HANDOFF_STATUSES,
    EVOLUTION_RECEIPT_FIELDS,
    EVOLUTION_RESULTS,
    EVOLUTION_SIGNAL_FIELDS,
    EXECUTION_PACKET_FIELDS,
    EXECUTION_RECEIPT_FIELDS,
    EXECUTION_RESULTS,
    GOVERNANCE_RECEIPT_FIELDS,
    GOVERNANCE_REQUEST_FIELDS,
    GOVERNANCE_RESULTS,
    GOVERNANCE_STAGES,
    HANDOFF_STATUSES,
    Iterable,
    KNOWLEDGE_HANDOFF_FIELDS,
    KNOWLEDGE_HANDOFF_PACKAGE_FIELDS,
    KNOWLEDGE_LEVELS,
    LEGACY_COMPATIBLE,
    MIDCOURSE_GATE_FIELDS,
    MIDCOURSE_GATE_RESULTS,
    MIDCOURSE_INITIAL_RESULTS,
    Mapping,
    OUTCOME_DECISIONS,
    PLAN_CONTRACT_SCHEMA_VERSION,
    PLAN_EXTENSION_KEY,
    PLAN_PACKAGE_FIELDS,
    PLATFORM_CANDIDATES,
    REVISION_TYPES,
    RISK_LEVELS,
    ROLLBACK_STATUSES,
    ROUTING_DECISION_FIELDS,
    ROUTING_PROVENANCE_FIELDS,
    SIDE_EFFECT_LEVELS,
    STATE_OWNERSHIP,
    STRUCTURAL_CHANGE_FIELDS,
    TASK_ENVELOPE_FIELDS,
    TASK_PRIORITIES,
    WORKFLOW_SCHEMA_VERSION,
    capability_invocation_mode,
    classify_version_change,
    contract_digest,
    contract_field_count,
    contract_fields,
    copy,
    governance_decision,
    merge_preserving_unknown,
    next_version,
    re,
    read_workflow_compatibility,
    receipt_idempotency_key,
    receipts_are_idempotent,
    stable_json,
    state_owner,
    validate_and_merge,
    validate_capability_ref,
    validate_checkpoint_ref,
    validate_condition,
    validate_content_ingest_receipt,
    validate_content_judgment,
    validate_contract,
    validate_evolution_receipt,
    validate_evolution_signal,
    validate_execution_packet,
    validate_execution_receipt,
    validate_governance_receipt,
    validate_governance_request,
    validate_knowledge_handoff,
    validate_knowledge_handoff_package,
    validate_knowledge_policy,
    validate_new_task_bundle,
    validate_plan_extension,
    validate_plan_package,
    validate_routing_decision,
    validate_task_envelope,
    workflow,
    _EMBEDDED_CONTENT_KEYS,
    _VALIDATORS,
    _bool,
    _enum,
    _evidence_refs,
    _id,
    _legacy_defaults,
    _list,
    _list_of_objects,
    _nonempty,
    _nonempty_list,
    _nonempty_policy,
    _nullable_ref,
    _object,
    _object_or_string,
    _optional_id,
    _optional_ref,
    _phase,
    _policy,
    _ref_or_object,
    _reject_embedded_content,
    _required,
    _schema_version,
    _scope,
    _semver,
    _sha256,
    _string_list,
    _timestamp,
    _validate_conditions,
    _validate_count_map,
    _validate_execution_packet_revision,
    _validate_midcourse_fields,
    _validate_task_plan_refs,
    _validate_task_reference_fields,
)

__all__ = [
    "Any",
    "CAPABILITY_COMPATIBILITY",
    "CAPABILITY_REF_FIELDS",
    "CHECKPOINT_REF_FIELDS",
    "CHECKPOINT_STATUSES",
    "CONDITION_FIELDS",
    "CONDITION_STATUSES",
    "CONDITION_TYPES",
    "CONTENT_INGEST_RECEIPT_FIELDS",
    "CONTENT_JUDGMENT_REASON_CODES",
    "CONTENT_JUDGMENT_STATUSES",
    "CONTENT_RESULTS",
    "CONTRACT_FIELD_SETS",
    "CONTRACT_ID_RE",
    "CONTRACT_KINDS",
    "CURRENT_CONTRACT",
    "E0_RESULTS",
    "EVOLUTION_HANDOFF_STATUSES",
    "EVOLUTION_RECEIPT_FIELDS",
    "EVOLUTION_RESULTS",
    "EVOLUTION_SIGNAL_FIELDS",
    "EXECUTION_PACKET_FIELDS",
    "EXECUTION_RECEIPT_FIELDS",
    "EXECUTION_RESULTS",
    "GOVERNANCE_RECEIPT_FIELDS",
    "GOVERNANCE_REQUEST_FIELDS",
    "GOVERNANCE_RESULTS",
    "GOVERNANCE_STAGES",
    "HANDOFF_STATUSES",
    "Iterable",
    "KNOWLEDGE_HANDOFF_FIELDS",
    "KNOWLEDGE_HANDOFF_PACKAGE_FIELDS",
    "KNOWLEDGE_LEVELS",
    "LEGACY_COMPATIBLE",
    "MIDCOURSE_GATE_FIELDS",
    "MIDCOURSE_GATE_RESULTS",
    "MIDCOURSE_INITIAL_RESULTS",
    "Mapping",
    "OUTCOME_DECISIONS",
    "PLAN_CONTRACT_SCHEMA_VERSION",
    "PLAN_EXTENSION_KEY",
    "PLAN_PACKAGE_FIELDS",
    "PLATFORM_CANDIDATES",
    "REVISION_TYPES",
    "RISK_LEVELS",
    "ROLLBACK_STATUSES",
    "ROUTING_DECISION_FIELDS",
    "ROUTING_PROVENANCE_FIELDS",
    "SIDE_EFFECT_LEVELS",
    "STATE_OWNERSHIP",
    "STRUCTURAL_CHANGE_FIELDS",
    "TASK_ENVELOPE_FIELDS",
    "TASK_PRIORITIES",
    "WORKFLOW_SCHEMA_VERSION",
    "capability_invocation_mode",
    "classify_version_change",
    "contract_digest",
    "contract_field_count",
    "contract_fields",
    "copy",
    "governance_decision",
    "merge_preserving_unknown",
    "next_version",
    "re",
    "read_workflow_compatibility",
    "receipt_idempotency_key",
    "receipts_are_idempotent",
    "stable_json",
    "state_owner",
    "validate_and_merge",
    "validate_capability_ref",
    "validate_checkpoint_ref",
    "validate_condition",
    "validate_content_ingest_receipt",
    "validate_content_judgment",
    "validate_contract",
    "validate_evolution_receipt",
    "validate_evolution_signal",
    "validate_execution_packet",
    "validate_execution_receipt",
    "validate_governance_receipt",
    "validate_governance_request",
    "validate_knowledge_handoff",
    "validate_knowledge_handoff_package",
    "validate_knowledge_policy",
    "validate_new_task_bundle",
    "validate_plan_extension",
    "validate_plan_package",
    "validate_routing_decision",
    "validate_task_envelope",
    "workflow",
]

# Facade delegation class for test mock compatibility
import types

class _FacadeModule(types.ModuleType):
    def __getattribute__(self, name):
        if name.startswith("_FacadeModule__") or name in {"__class__", "__dict__", "__weakref__", "__module__", "__name__", "__doc__", "__file__", "__path__", "__package__", "__all__"}:
            return super().__getattribute__(name)
        try:
            target = sys.modules["pwf_governed._legacy.plan_contracts"]
            val = getattr(target, name)
            return val
        except (KeyError, AttributeError):
            return super().__getattribute__(name)

    def __setattr__(self, name, value):
        if name.startswith("_FacadeModule__") or name in {"__class__", "__dict__", "__weakref__", "__module__", "__name__", "__doc__", "__file__", "__path__", "__package__", "__loader__", "__spec__", "__all__"}:
            super().__setattr__(name, value)
        else:
            try:
                target = sys.modules["pwf_governed._legacy.plan_contracts"]
                setattr(target, name, value)
            except (KeyError, AttributeError):
                super().__setattr__(name, value)

    def __delattr__(self, name):
        try:
            target = sys.modules["pwf_governed._legacy.plan_contracts"]
            delattr(target, name)
        except (KeyError, AttributeError):
            super().__delattr__(name)

sys.modules[__name__].__class__ = _FacadeModule
